version: '3.3'

services:
  app:
    build: .
    command: gunicorn -w 12 MegaMarket.wsgi:application --bind 0:80
    expose:
      - 80
    env_file:
      - ./MegaMarket/.env
    restart: always
    depends_on:
      - db
  db:
    image: postgres:14.2
    expose:
      - 5432
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./MegaMarket/.env
    restart: always
  nginx:
    build: nginx/.
    ports:
      - 80:80
    restart: always
    depends_on:
      - app