# Generated by Django 4.0.5 on 2022-06-17 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUnit',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(max_length=2048, verbose_name='Имя товара/категории')),
                ('date', models.CharField(max_length=32, verbose_name='Время последнего обновления элемента')),
                ('unit_type', models.CharField(choices=[('OFFER', 'Offer'), ('CATEGORY', 'Category')], max_length=8, verbose_name='Тип элемента - категория или товар')),
                ('price', models.PositiveBigIntegerField(default=None, null=True, verbose_name='Целое число, для категории - это средняя цена всех дочерних товаров')),
                ('parent', models.ForeignKey(db_column='parent', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_unit.shopunit')),
            ],
        ),
        migrations.CreateModel(
            name='ShopUnitStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Имя товара/категории')),
                ('date', models.CharField(max_length=32, verbose_name='Время последнего обновления элемента')),
                ('parentId', models.UUIDField(db_index=True, default=None, null=True, verbose_name='UUID родительской категории')),
                ('unit_type', models.CharField(choices=[('OFFER', 'Offer'), ('CATEGORY', 'Category')], max_length=8, verbose_name='Тип элемента - категория или товар')),
                ('price', models.PositiveBigIntegerField(default=None, null=True, verbose_name='Целое число, для категории - это средняя цена всех дочерних товаров')),
                ('shop_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_unit.shopunit')),
            ],
        ),
    ]
