# Generated by Django 4.0.5 on 2022-06-17 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_unit.shopunit'),
        ),
    ]
