# Generated by Django 4.0.5 on 2022-06-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_unit', '0002_alter_shopunit_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='date',
            field=models.DateTimeField(verbose_name='Время последнего обновления элемента'),
        ),
    ]
