# Generated by Django 4.0.5 on 2022-06-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_unit', '0003_alter_shopunit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunitstatistic',
            name='date',
            field=models.DateTimeField(verbose_name='Время последнего обновления элемента'),
        ),
    ]
