# Generated by Django 4.0.5 on 2022-06-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_unit', '0004_alter_shopunitstatistic_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopunitstatistic',
            old_name='parentId',
            new_name='parent_id',
        ),
    ]
